apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: example-rules
    role: alert-rules
  name: prom
spec:
  groups:
    - name: trivy_group
      rules:
      - alert: trivy_unhealthy
        expr: sum by (namespace, pod)(kube_pod_status_phase{phase=~"Unknown|Failed", namespace="trivy-system"}) != 0
        for: 30s
        labels:
          severity: critical
        annotations:
          description: Trivy container is unhealthy for more than 30 seconds.
          summary: Trivy unhealthy
          type: Container
      - alert: trivy_container_restarts
        expr: increase(kube_pod_container_status_restarts_total{namespace="trivy-system"}[5m]) > 3
        for: 1m
        labels:
          severity: warning
        annotations:
          description: Trivy container has restarted more than 3 times in the last 5 minutes.
        summary: Trivy container instability
      
      - alert: trivy_new_critical_vuln
        expr: sum(trivy_image_vulnerabilities{severity="Critical", namespace="test"}) > 0
        for: 30s
        labels:
          severity: critical
        annotations:
          description: Trivy found a new CRITICAL vulnerability in a deployed container image
          summary: Trivy new CRITICAL vulnerability
          type: CRD
